<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Анализатор страниц</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/css/bootstrap.min.css" rel="stylesheet"
                    integrity="sha384-SgOJa3DmI69IUzQ2PVdRZhwQ+dy64/BUtbMJw1MZ8t5HZApcHrRKUc4W0kG879m7"
                    crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.5/dist/js/bootstrap.bundle.min.js"
                    integrity="sha384-k6d4wzSIapyDyv1kpU366/PK5hCdSbCRGRCMv+eplOQJWyd1fbcAu9OCUj5zNLiq"
                    crossorigin="anonymous"></script>

</head>


<body>
    <nav class="menu">
      <ul>
        <li><a href="/">Анализатор страниц</a></li>
        <li><a href="/">Главная</a></li>
        <li><a href="/urls">Сайты</a></li>
      </ul>
    </nav>


    <h1>Анализатор страниц</h1>
    <p>Бесплатно проверяйте сайты на SEO пригодность</p>

    <form>
    <p><input type="url" name="url" placeholder="Адрес сайта" size="18" /></p>
    <p>
    <button type="submit">Проверить</button>
    <button type="reset">Отмена</button>
    </p>
    </form>
</body>


</html>